<?php

declare(strict_types=1);

namespace Captainbi\Hyperf\Database\Connectors;

use Hyperf\Contract\SessionInterface;
use Hyperf\Contract\StdoutLoggerInterface;
use Hyperf\Di\Annotation\Inject;

class ConnectionFactory extends \Hyperf\Database\Connectors\ConnectionFactory
{

    public function make(array $config, $name = null)
    {
        $config = $this->parseConfig($config, $name);
        return parent::make($config, $name); // TODO: Change the autogenerated stub
    }

}