<?php

declare(strict_types=1);

namespace Captainbi\Hyperf\Session\Handler;

use Hyperf\Redis\Redis as RedisProxy;

class RedisHandler extends \Hyperf\Session\Handler\RedisHandler
{

    /**
     * @var string
     */
    protected $prefix = '';

    public function __construct($redis, int $gcMaxLifeTime, string $prefix)
    {
        $this->prefix = $prefix;
        parent::__construct($redis, $gcMaxLifeTime);
    }

    public function destroy($session_id)
    {
        $session_id = $this->prefix.$session_id;
        return parent::destroy($session_id); // TODO: Change the autogenerated stub
    }

    public function write($session_id, $session_data)
    {
        $session_id = $this->prefix.$session_id;
        return parent::write($session_id, $session_data); // TODO: Change the autogenerated stub
    }

    public function read($session_id)
    {
        $session_id = $this->prefix.$session_id;
        return parent::read($session_id); // TODO: Change the autogenerated stub
    }

}