<?php

declare(strict_types=1);
/**
 * This file is part of Hyperf.
 *
 * @link     https://www.hyperf.io
 * @document https://hyperf.wiki
 * @contact  group@hyperf.io
 * @license  https://github.com/hyperf/hyperf/blob/master/LICENSE
 */
namespace App\Controller;

use App\Service\SelectProductService;
use Captainbi\Hyperf\Util\Result;
use Hyperf\Di\Annotation\Inject;
use Hyperf\HttpServer\Annotation\Controller;
use Hyperf\HttpServer\Annotation\RequestMapping;
use Hyperf\HttpServer\Contract\RequestInterface;
use Hyperf\HttpServer\Contract\ResponseInterface;

/**
 * @Controller(prefix="select_product")
 * @OA\Info(title="中台",version="1.0")
 */
class SelectProductController extends BaseController
{
    /**
     * @Inject()
     * @var RequestInterface
     */
    protected $request;

    /**
     * @Inject()
     * @var ResponseInterface
     */
    protected $response;

    /**
     * @Inject()
     * @var SelectProductService
     */
    protected $service;

    /**
     * @OA\Get(
     *     path="/select_product/category_list",
     *     summary="选品分类列表",
     *     tags={"select_product"},
     *     @OA\Parameter(
     *          name="search_value",
     *          in="query",
     *          description="搜索值",
     *          @OA\Schema(type="string"),
     *     ),
     *     @OA\Parameter(
     *          name="country_id",
     *          required=true,
     *          in="query",
     *          description="国家id",
     *          @OA\Schema(type="integer")
     *     ),
     *     @OA\Parameter(
     *          name="offset",
     *          in="query",
     *          description="偏移量",
     *          @OA\Schema(type="integer")
     *     ),
     *     @OA\Parameter(
     *          name="limit",
     *          in="query",
     *          description="分页个数",
     *          @OA\Schema(type="integer")
     *     ),
     *     @OA\Parameter(
     *          name="level",
     *          in="query",
     *          description="分类级别,多个逗号隔开",
     *          @OA\Schema(type="string")
     *     ),
     *     @OA\Response(response=200,
     *          description="获取成功",
     *             @OA\MediaType(mediaType="application/json",
     *                  @OA\Schema(
     *                      @OA\Property(
     *                          property="code",
     *                          type="integer",
     *                          description="200",
     *                          example="200"
     *                      ),
     *                      @OA\Property(
     *                          property="msg",
     *                          type="string",
     *                          description="msg"
     *                      ),
     *                      @OA\Property(
     *                             property="data",
     *                             type="object",
     *                             @OA\Property(
     *                                 property="num",
     *                                 type="integer",
     *                                 description="总数"
     *                              ),
     *                               @OA\Property(
     *                                 property="list",
     *                                 type="array",
     *                                  @OA\Items(
     *                                      @OA\Property(
     *                                         property="category",
     *                                         type="string",
     *                                         description="分类"
     *                                       ),
     *                                       @OA\Property(
     *                                          property="category_id",
     *                                           type="integer",
     *                                           description="分类id"
     *                                       ),
     *                                       @OA\Property(
     *                                           property="path",
     *                                           type="array",
     *                                          @OA\Items(
     *                                               @OA\Property(
     *                                                   property="level",
     *                                                   type="integer",
     *                                                   description="分类级别"
     *                                               ),
     *                                              @OA\Property(
     *                                                 property="cate_id",
     *                                                 type="integer",
     *                                                 description="分类id"
     *                                              ),
     *                                               @OA\Property(
     *                                                   property="cate_name",
     *                                                    type="string",
     *                                                    description="分类名"
     *                                                 )
     *                                              )
     *                                          )
     *                                   )
     *                               )
     *
     *                       )
     *
     *                   )
     *               )
     *       )
     * )
     *
     * @RequestMapping(path="category_list", methods="get")
     * @return mixed
     */
    public function categoryList()
    {
        $request_data = $this->request->all();
        $data =$this->service->category_list($request_data);

        if($data['code']== 0){
            return Result::fail([], $data['msg']);
        }
        return Result::success($data['data'],$data['msg']);

    }


    /**
     * @OA\Post(
     *     path="/select_product/product_list",
     *     summary="选品商品列表",
     *     tags={"select_product"},
     *     @OA\RequestBody(
     *         @OA\MediaType(
     *             mediaType="application/x-www-form-urlencoded",
     *             @OA\Schema(required={"country_id"},
     *                  @OA\Property(
     *                      property="product_id",
     *                       type="string",
     *                       description="商品id,多个逗号分隔"
     *                   ),
     *                   @OA\Property(
     *                        property="country_id",
     *                         type="integer",
     *                          description="国家id"
     *                    ),
     *                    @OA\Property(
     *                          property="category_id",
     *                           type="string",
     *                            description="分类id,多个逗号分隔"
     *                    ),
     *                     @OA\Property(
     *                          property="min_month_salesamount",
     *                           type="integer",
     *                           description="最小月销量"
     *                      ),
     *                      @OA\Property(
     *                            property="max_month_salesamount",
     *                            type="integer",
     *                            description="最大月销量"
     *                       ),
     *                       @OA\Property(
     *                            property="min_month_revenue",
     *                             type="number",
     *                             description="最小月销售额"
     *                       ),
     *                      @OA\Property(
     *                             property="max_month_revenue",
     *                              type="number",
     *                              description="最大月销售额"
     *                       ),
     *                      @OA\Property(
     *                               property="asin_price_min",
     *                               type="number",
     *                               description="最小价格"
     *                      ),
     *                    @OA\Property(
     *                       property="asin_price_max",
     *                       type="number",
     *                      description="最大价格"
     *                   ),
     *                  @OA\Property(
     *                     property="min_customer_reviews",
     *                     type="integer",
     *                     description="最小评论数"
     *                 ),
     *                  @OA\Property(
     *                     property="max_customer_reviews",
     *                     type="integer",
     *                     description="最大评论数"
     *                 ),
     *                  @OA\Property(
     *                     property="min_score",
     *                     type="number",
     *                     description="最小星级"
     *                 ),
     *                  @OA\Property(
     *                     property="max_score",
     *                     type="number",
     *                     description="最大星级"
     *                 ),
     *                  @OA\Property(
     *                     property="min_best_sellers_rank",
     *                     type="integer",
     *                     description="最小BSR"
     *                 ),
     *                  @OA\Property(
     *                     property="max_best_sellers_rank",
     *                     type="integer",
     *                     description="最大BSR"
     *                 ),
     *                  @OA\Property(
     *                     property="min_follow_sellers_num",
     *                     type="integer",
     *                     description="最小卖家数"
     *                 ),
     *                  @OA\Property(
     *                     property="max_follow_sellers_num",
     *                     type="integer",
     *                     description="最大卖家数"
     *                 ),
     *                  @OA\Property(
     *                     property="is_best_seller",
     *                     type="integer",
     *                     description="是否best_seller"
     *                 ),
     *                  @OA\Property(
     *                     property="is_brand",
     *                     type="integer",
     *                     description="是否有品牌名称"
     *                 ),
     *                  @OA\Property(
     *                     property="chinese_sellers",
     *                     type="integer",
     *                     description="是否中国卖家"
     *                 ),
     *                  @OA\Property(
     *                     property="is_ama_choice",
     *                     type="integer",
     *                     description="是否amazon choice"
     *                 ),
     *                  @OA\Property(
     *                     property="delivery",
     *                     type="integer",
     *                     description="配送类型：0:FBA 1:FBM 2:AMZ"
     *                 ),
     *                  @OA\Property(
     *                     property="offset",
     *                     type="integer",
     *                     description="偏移量"
     *                 ),
     *                  @OA\Property(
     *                     property="limit",
     *                     type="integer",
     *                     description="每页条数"
     *                 )
     *             )
     *         )
     *     ),
     *     @OA\Response(response=200,
     *          description="获取成功",
     *             @OA\MediaType(mediaType="application/json",
     *                  @OA\Schema(
     *                       @OA\Property(
     *                          property="code",
     *                          type="integer",
     *                          description="200",
     *                          example="200"
     *                      ),
     *                      @OA\Property(
     *                          property="msg",
     *                          type="string",
     *                          description="msg"
     *                      ),
     *                      @OA\Property(
     *                          property="data",
     *                          type="object",
     *                          @OA\Property(
     *                              property="num",
     *                              type="integer",
     *                              description="总数"
     *                           ),
     *                          @OA\Property(
     *                              property="list",
     *                              type="array",
     *                              @OA\Items(
     *                                @OA\Property(
     *                                   property="product_id",
     *                                   type="string",
     *                                   description="商品id"
     *                                ),
     *                               @OA\Property(
     *                                   property="asin",
     *                                   type="string",
     *                                    description="asin'"
     *                                ),
     *                              @OA\Property(
     *                                   property="category_id",
     *                                   type="integer",
     *                                    description="分类id"
     *                                ),
     *                             @OA\Property(
     *                                property="title",
     *                                 type="string",
     *                                 description="标题"
     *                              ),
     *                            @OA\Property(
     *                                 property="category",
     *                                type="string",
     *                                description="分类名"
     *                           ),
     *                            @OA\Property(
     *                                 property="asin_price_min",
     *                                 type="number",
     *                                description="价格"
     *                              ),
     *                            @OA\Property(
     *                                 property="best_sellers_rank",
     *                                type="integer",
     *                                description="卖家商品排名"
     *                           ),
     *                            @OA\Property(
     *                                  property="month_salesamount",
     *                                 type="integer",
     *                                 description="预估月销量"
     *                             ),
     *                           @OA\Property(
     *                               property="month_revenue",
     *                                type="number",
     *                                description="预估月销售额"
     *                            ),
     *                            @OA\Property(
     *                                  property="customer_reviews",
     *                                 type="integer",
     *                                  description="评论数"
     *                           ),
     *                             @OA\Property(
     *                               property="score",
     *                                type="number",
     *                                 description="星级"
     *                           ),
     *                            @OA\Property(
     *                                 property="delivery",
     *                                type="integer",
     *                                description="配送（0:FBA 1:FBM 2:AMZ）"
     *                             ),
     *                            @OA\Property(
     *                                  property="is_best_seller",
     *                                 type="integer",
     *                                  description="是否best_seller"
     *                             ),
     *                            @OA\Property(
     *                               property="chinese_sellers",
     *                                type="integer",
     *                                description="是否中国卖家"
     *                              ),
     *                             @OA\Property(
     *                                  property="is_ama_choice",
     *                                  type="integer",
     *                                description="是否amazon choice"
     *                              ),
     *                            @OA\Property(
     *                               property="path",
     *                                type="array",
     *                               @OA\Items(
     *                                 @OA\Property(
     *                                    property="level",
     *                                     type="integer",
     *                                      description="分类级别"
     *                                 ),
     *                                 @OA\Property(
     *                                       property="cate_id",
     *                                       type="integer",
     *                                       description="分类id"
     *                                  ),
     *                                  @OA\Property(
     *                                       property="cate_name",
     *                                       type="string",
     *                                       description="分类名"
     *                                   )
     *                                )
     *                               ),
     *                                @OA\Property(
     *                                   property="shipping_weight",
     *                                  type="number",
     *                                   description="重量"
     *                               ),
     *                               @OA\Property(
     *                                   property="follow_sellers_num",
     *                                  type="integer",
     *                                   description="卖家数"
     *                              ),
     *                                @OA\Property(
     *                                   property="img_url",
     *                                   type="string",
     *                                   description="图片"
     *                                 ),
     *                                @OA\Property(
     *                                   property="brand",
     *                                    type="string",
     *                                   description="分类"
     *                               )
     *                        )
     *                      )
     *                  )
     *               )
     *          )
     *       )
     * )
     *
     *
     * @RequestMapping(path="product_list", methods="post")
     * @return mixed
     */
    public function productList()
    {
        $request_data = $this->request->all();
        $data =$this->service->product_list($request_data);
        if($data['code']== 0){
            return Result::fail([], $data['msg']);
        }
        return Result::success($data['data'],$data['msg']);

    }


    /**
     * @OA\Post(
     *     path="/select_product/market_list",
     *     summary="选品市场列表",
     *     tags={"select_product"},
     *     @OA\RequestBody(
     *         @OA\MediaType(
     *             mediaType="application/x-www-form-urlencoded",
     *             @OA\Schema(required={"country_id"},
     *                 @OA\Property(
     *                     property="country_id",
     *                     type="integer",
     *                     description="国家id"
     *                 ),
     *                 @OA\Property(
     *                     property="category_id",
     *                     type="string",
     *                     description="分类id,多个逗号分隔"
     *                 ),
     *                  @OA\Property(
     *                     property="min_category_estimate_month_sales",
     *                     type="integer",
     *                     description="最小分类月销量"
     *                 ),
     *                  @OA\Property(
     *                     property="max_category_estimate_month_sales",
     *                     type="integer",
     *                     description="最大分类月销量"
     *                 ),
     *                  @OA\Property(
     *                     property="min_category_estimate_month_sales_volume",
     *                     type="number",
     *                     description="最小分类月销售额"
     *                 ),
     *                  @OA\Property(
     *                     property="max_category_estimate_month_sales_volume",
     *                     type="number",
     *                     description="最大分类月销售额"
     *                 ),
     *                  @OA\Property(
     *                     property="min_category_sum",
     *                     type="integer",
     *                     description="最小商品总数"
     *                 ),
     *                  @OA\Property(
     *                     property="max_category_sum",
     *                     type="integer",
     *                     description="最大商品总数"
     *                 ),
     *                  @OA\Property(
     *                     property="min_category_all_average_score",
     *                     type="number",
     *                     description="最小平均星级"
     *                 ),
     *                  @OA\Property(
     *                     property="max_category_all_average_score",
     *                     type="number",
     *                     description="最大平均星级"
     *                 ),
     *                  @OA\Property(
     *                     property="min_category_all_average_BSR_rank",
     *                     type="number",
     *                     description="最小平均BSR"
     *                 ),
     *                  @OA\Property(
     *                     property="max_category_all_average_BSR_rank",
     *                     type="number",
     *                     description="最大平均BSR"
     *                 ),
     *                  @OA\Property(
     *                     property="min_category_all_average_price",
     *                     type="number",
     *                     description="最小平均价格"
     *                 ),
     *                  @OA\Property(
     *                     property="max_category_all_average_price",
     *                     type="number",
     *                     description="最大平均价格"
     *                 ),
     *                  @OA\Property(
     *                     property="min_category_all_average_weight",
     *                     type="number",
     *                     description="最小平均重量"
     *                 ),
     *                  @OA\Property(
     *                     property="max_category_all_average_weight",
     *                     type="number",
     *                     description="最大平均重量"
     *                 ),
     *                  @OA\Property(
     *                     property="min_customer_reviews",
     *                     type="number",
     *                     description="最小平均评论数"
     *                 ),
     *                  @OA\Property(
     *                     property="max_customer_reviews",
     *                     type="number",
     *                     description="最大平均评论数"
     *                 ),
     *                  @OA\Property(
     *                     property="min_category_all_average_variants_num",
     *                     type="number",
     *                     description="最小平均变体数"
     *                 ),
     *                  @OA\Property(
     *                     property="max_category_all_average_variants_num",
     *                     type="number",
     *                     description="最大平均变体数"
     *                 ),
     *                  @OA\Property(
     *                     property="min_category_brands_sum",
     *                     type="integer",
     *                     description="最小品牌数量"
     *                 ),
     *                  @OA\Property(
     *                     property="max_category_brands_sum",
     *                     type="integer",
     *                     description="最大品牌数量"
     *                 ),
     *                  @OA\Property(
     *                     property="min_category_brands_sum_percent",
     *                     type="number",
     *                     description="最小品牌占比"
     *                 ),
     *                  @OA\Property(
     *                     property="max_category_brands_sum_percent",
     *                     type="number",
     *                     description="最大品牌占比"
     *                 ),
     *                  @OA\Property(
     *                     property="min_category_FBA_sum_percent",
     *                     type="number",
     *                     description="最小FBA商品占比"
     *                 ),
     *                  @OA\Property(
     *                     property="max_category_FBA_sum_percent",
     *                     type="number",
     *                     description="最大FBA商品占比"
     *                 ),
     *                  @OA\Property(
     *                     property="min_category_FBM_sum_percent",
     *                     type="number",
     *                     description="最小FBM商品占比"
     *                 ),
     *                  @OA\Property(
     *                     property="max_category_FBM_sum_percent",
     *                     type="number",
     *                     description="最大FBM商品占比"
     *                 ),
     *                  @OA\Property(
     *                     property="min_category_AMZautarky_sum_percent",
     *                     type="number",
     *                     description="最小Amazon商品占比"
     *                 ),
     *                  @OA\Property(
     *                     property="max_category_AMZautarky_sum_percent",
     *                     type="number",
     *                     description="最大Amazon商品占比"
     *                 ),
     *                  @OA\Property(
     *                     property="min_category_chinese_saler_count_percent",
     *                     type="number",
     *                     description="最小中国卖家占比"
     *                 ),
     *                  @OA\Property(
     *                     property="max_category_chinese_saler_count_percent",
     *                     type="number",
     *                     description="最大中国卖家占比"
     *                 ),
     *                  @OA\Property(
     *                     property="offset",
     *                     type="integer",
     *                     description="偏移量"
     *                 ),
     *                  @OA\Property(
     *                     property="limit",
     *                     type="integer",
     *                     description="每页条数"
     *                 )
     *             )
     *         )
     *     ),
     *     @OA\Response(response=200,
     *          description="获取成功",
     *             @OA\MediaType(mediaType="application/json",
     *                  @OA\Schema(
     *                      @OA\Property(
     *                          property="code",
     *                          type="integer",
     *                          description="200",
     *                          example="200"
     *                      ),
     *                      @OA\Property(
     *                          property="msg",
     *                          type="string",
     *                          description="msg"
     *                      ),
     *                      @OA\Property(
     *                          property="data",
     *                          type="object",
     *                          @OA\Property(
     *                              property="num",
     *                              type="integer",
     *                              description="总数"
     *                           ),
     *                          @OA\Property(
     *                              property="list",
     *                              type="array",
     *                              @OA\Items(
     *                                 @OA\Property(
     *                                     property="cate_name",
     *                                      type="string",
     *                                       description="分类名称"
     *                                ),
     *                                @OA\Property(
     *                                    property="cate_name_trans",
     *                                      type="string",
     *                                   description="分类名称翻译'"
     *                                 ),
     *                                 @OA\Property(
     *                                    property="cate_id",
     *                                    type="integer",
     *                                     description="分类id"
     *                                  ),
     *                               @OA\Property(
     *                                     property="category_estimate_month_sales",
     *                                    type="integer",
     *                                      description="月总销量"
     *                                ),
     *                               @OA\Property(
     *                                      property="category_month_average_sales",
     *                                     type="number",
     *                                   description="月均销量"
     *                                 ),
     *                                @OA\Property(
     *                                    property="category_month_average_sales_volume",
     *                                     type="number",
     *                                     description="月均销售额"
     *                                 ),
     *                               @OA\Property(
     *                                   property="category_all_average_price",
     *                                   type="number",
     *                                   description="平均价格"
     *                              ),
     *                               @OA\Property(
     *                                    property="category_top100_average_price",
     *                                    type="number",
     *                                     description="前一百平均价格"
     *                                 ),
     *                               @OA\Property(
     *                                    property="category_all_average_customer_reviews",
     *                                     type="number",
     *                                      description="平均评论数"
     *                                 ),
     *                               @OA\Property(
     *                                    property="category_top100_average_customer_reviews",
     *                                      type="number",
     *                                      description="前一百平均评论数"
     *                                ),
     *                               @OA\Property(
     *                                 property="category_top100_average_score",
     *                                 type="number",
     *                                 description="前一百平均星级"
     *                                ),
     *                            @OA\Property(
     *                                 property="category_all_average_score",
     *                                  type="number",
     *                                   description="平均星级"
     *                               ),
     *                             @OA\Property(
     *                                property="category_top100_average_ranking",
     *                                 type="number",
     *                                 description="前一百平均BSR"
     *                              ),
     *                            @OA\Property(
     *                                 property="category_all_average_BSR_rank",
     *                                type="number",
     *                                  description="平均BSR"
     *                           ),
     *                           @OA\Property(
     *                                 property="category_exist_brands_sum_percent",
     *                                  type="number",
     *                                  description="品牌占比"
     *                              ),
     *                           @OA\Property(
     *                                  property="category_FBA_saler_count_percent",
     *                                  type="number",
     *                                  description="FBA占比"
     *                           ),
     *                           @OA\Property(
     *                               property="category_FBM_saler_count_percent",
     *                                 type="number",
     *                               description="FBM占比"
     *                           ),
     *                           @OA\Property(
     *                                 property="category_AMZ_saler_count_percent",
     *                                  type="number",
     *                                  description="AMZ占比"
     *                            ),
     *                           @OA\Property(
     *                                 property="category_chinese_saler_count_percent",
     *                                type="number",
     *                                 description="中国卖家占比"
     *                           ),
     *                           @OA\Property(
     *                                property="category_sum",
     *                               type="number",
     *                               description="商品数量"
     *                           ),
     *                           @OA\Property(
     *                                 property="category_all_average_weight",
     *                                  type="number",
     *                                  description="平均重量"
     *                           ),
     *                            @OA\Property(
     *                                  property="category_all_average_variants_num",
     *                                 type="number",
     *                                 description="平均变体数"
     *                            ),
     *                            @OA\Property(
     *                                property="path",
     *                                type="array",
     *                                @OA\Items(
     *                                     @OA\Property(
     *                                        property="level",
     *                                         type="integer",
     *                                        description="分类级别"
     *                                       ),
     *                                   @OA\Property(
     *                                         property="cate_id",
     *                                         type="integer",
     *                                        description="分类id"
     *                                   ),
     *                                   @OA\Property(
     *                                         property="cate_name",
     *                                       type="string",
     *                                        description="分类名"
     *                                   )
     *                                )
     *                             )
     *                      )
     *                   )
     *                )
     *            )
     *       )
     *    )
     * )
     *
     * @RequestMapping(path="market_list", methods="post")
     * @return mixed
     */
    public function marketList()
    {
        $request_data = $this->request->all();
        $data =$this->service->market_list($request_data);

        if($data['code']== 0){
            return Result::fail([], $data['msg']);
        }
        return Result::success($data['data'],$data['msg']);

    }
}
