<?php

declare(strict_types=1);
/**
 * This file is part of Hyperf.
 *
 * @link     https://www.hyperf.io
 * @document https://hyperf.wiki
 * @contact  group@hyperf.io
 * @license  https://github.com/hyperf/hyperf/blob/master/LICENSE
 */
return [
    'default' => [
        'driver' => env('DB_DRIVER', 'mysql'),
        'host' => env('DB_HOST', 'localhost'),
        'database' => env('DB_DATABASE', 'hyperf'),
        'port' => env('DB_PORT', 3306),
        'username' => env('DB_USERNAME', 'root'),
        'password' => env('DB_PASSWORD', ''),
        'charset' => env('DB_CHARSET', 'utf8'),
        'collation' => env('DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ],
    "erp_base" => [
        'driver' => env('BASE_DB_DRIVER', 'mysql'),
        'host' => env('BASE_DB_HOST', 'localhost'),
        'database' => env('BASE_DB_DATABASE', 'hyperf'),
        'port' => env('BASE_DB_PORT', 3306),
        'username' => env('BASE_DB_USERNAME', 'root'),
        'password' => env('BASE_DB_PASSWORD', ''),
        'charset' => env('BASE_DB_CHARSET', 'utf8'),
        'collation' => env('BASE_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('BASE_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_captain_001" => [
        'driver' => env('CAPTAIN001_DB_DRIVER', 'mysql'),
        'host' => env('CAPTAIN001_DB_HOST', 'localhost'),
        'database' => env('CAPTAIN001_DB_DATABASE', 'hyperf'),
        'port' => env('CAPTAIN001_DB_PORT', 3306),
        'username' => env('CAPTAIN001_DB_USERNAME', 'root'),
        'password' => env('CAPTAIN001_DB_PASSWORD', ''),
        'charset' => env('CAPTAIN001_DB_CHARSET', 'utf8'),
        'collation' => env('CAPTAIN001_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('CAPTAIN001_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('CAPTAIN001_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_captain_002" => [
        'driver' => env('CAPTAIN002_DB_DRIVER', 'mysql'),
        'host' => env('CAPTAIN002_DB_HOST', 'localhost'),
        'database' => env('CAPTAIN002_DB_DATABASE', 'hyperf'),
        'port' => env('CAPTAIN002_DB_PORT', 3306),
        'username' => env('CAPTAIN002_DB_USERNAME', 'root'),
        'password' => env('CAPTAIN002_DB_PASSWORD', ''),
        'charset' => env('CAPTAIN002_DB_CHARSET', 'utf8'),
        'collation' => env('CAPTAIN002_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('CAPTAIN002_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('CAPTAIN002_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_captain_003" => [
        'driver' => env('CAPTAIN003_DB_DRIVER', 'mysql'),
        'host' => env('CAPTAIN003_DB_HOST', 'localhost'),
        'database' => env('CAPTAIN003_DB_DATABASE', 'hyperf'),
        'port' => env('CAPTAIN003_DB_PORT', 3306),
        'username' => env('CAPTAIN003_DB_USERNAME', 'root'),
        'password' => env('CAPTAIN003_DB_PASSWORD', ''),
        'charset' => env('CAPTAIN003_DB_CHARSET', 'utf8'),
        'collation' => env('CAPTAIN003_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('CAPTAIN003_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('CAPTAIN003_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_captain_004" => [
        'driver' => env('CAPTAIN004_DB_DRIVER', 'mysql'),
        'host' => env('CAPTAIN004_DB_HOST', 'localhost'),
        'database' => env('CAPTAIN004_DB_DATABASE', 'hyperf'),
        'port' => env('CAPTAIN004_DB_PORT', 3306),
        'username' => env('CAPTAIN004_DB_USERNAME', 'root'),
        'password' => env('CAPTAIN004_DB_PASSWORD', ''),
        'charset' => env('CAPTAIN004_DB_CHARSET', 'utf8'),
        'collation' => env('CAPTAIN004_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('CAPTAIN004_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('CAPTAIN004_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_captain_005" => [
        'driver' => env('CAPTAIN005_DB_DRIVER', 'mysql'),
        'host' => env('CAPTAIN005_DB_HOST', 'localhost'),
        'database' => env('CAPTAIN005_DB_DATABASE', 'hyperf'),
        'port' => env('CAPTAIN005_DB_PORT', 3306),
        'username' => env('CAPTAIN005_DB_USERNAME', 'root'),
        'password' => env('CAPTAIN005_DB_PASSWORD', ''),
        'charset' => env('CAPTAIN005_DB_CHARSET', 'utf8'),
        'collation' => env('CAPTAIN005_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('CAPTAIN005_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('CAPTAIN005_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_captain_006" => [
        'driver' => env('CAPTAIN006_DB_DRIVER', 'mysql'),
        'host' => env('CAPTAIN006_DB_HOST', 'localhost'),
        'database' => env('CAPTAIN006_DB_DATABASE', 'hyperf'),
        'port' => env('CAPTAIN006_DB_PORT', 3306),
        'username' => env('CAPTAIN006_DB_USERNAME', 'root'),
        'password' => env('CAPTAIN006_DB_PASSWORD', ''),
        'charset' => env('CAPTAIN006_DB_CHARSET', 'utf8'),
        'collation' => env('CAPTAIN006_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('CAPTAIN006_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('CAPTAIN006_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_captain_007" => [
        'driver' => env('CAPTAIN007_DB_DRIVER', 'mysql'),
        'host' => env('CAPTAIN007_DB_HOST', 'localhost'),
        'database' => env('CAPTAIN007_DB_DATABASE', 'hyperf'),
        'port' => env('CAPTAIN007_DB_PORT', 3306),
        'username' => env('CAPTAIN007_DB_USERNAME', 'root'),
        'password' => env('CAPTAIN007_DB_PASSWORD', ''),
        'charset' => env('CAPTAIN007_DB_CHARSET', 'utf8'),
        'collation' => env('CAPTAIN007_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('CAPTAIN007_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('CAPTAIN007_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_captain_008" => [
        'driver' => env('CAPTAIN008_DB_DRIVER', 'mysql'),
        'host' => env('CAPTAIN008_DB_HOST', 'localhost'),
        'database' => env('CAPTAIN008_DB_DATABASE', 'hyperf'),
        'port' => env('CAPTAIN008_DB_PORT', 3306),
        'username' => env('CAPTAIN008_DB_USERNAME', 'root'),
        'password' => env('CAPTAIN008_DB_PASSWORD', ''),
        'charset' => env('CAPTAIN008_DB_CHARSET', 'utf8'),
        'collation' => env('CAPTAIN008_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('CAPTAIN008_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('CAPTAIN008_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_captain_009" => [
        'driver' => env('CAPTAIN009_DB_DRIVER', 'mysql'),
        'host' => env('CAPTAIN009_DB_HOST', 'localhost'),
        'database' => env('CAPTAIN009_DB_DATABASE', 'hyperf'),
        'port' => env('CAPTAIN009_DB_PORT', 3306),
        'username' => env('CAPTAIN009_DB_USERNAME', 'root'),
        'password' => env('CAPTAIN009_DB_PASSWORD', ''),
        'charset' => env('CAPTAIN009_DB_CHARSET', 'utf8'),
        'collation' => env('CAPTAIN009_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('CAPTAIN009_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('CAPTAIN009_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_captain_010" => [
        'driver' => env('CAPTAIN010_DB_DRIVER', 'mysql'),
        'host' => env('CAPTAIN010_DB_HOST', 'localhost'),
        'database' => env('CAPTAIN010_DB_DATABASE', 'hyperf'),
        'port' => env('CAPTAIN010_DB_PORT', 3306),
        'username' => env('CAPTAIN010_DB_USERNAME', 'root'),
        'password' => env('CAPTAIN010_DB_PASSWORD', ''),
        'charset' => env('CAPTAIN010_DB_CHARSET', 'utf8'),
        'collation' => env('CAPTAIN010_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('CAPTAIN010_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('CAPTAIN010_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_captain_011" => [
        'driver' => env('CAPTAIN011_DB_DRIVER', 'mysql'),
        'host' => env('CAPTAIN011_DB_HOST', 'localhost'),
        'database' => env('CAPTAIN011_DB_DATABASE', 'hyperf'),
        'port' => env('CAPTAIN011_DB_PORT', 3306),
        'username' => env('CAPTAIN011_DB_USERNAME', 'root'),
        'password' => env('CAPTAIN011_DB_PASSWORD', ''),
        'charset' => env('CAPTAIN011_DB_CHARSET', 'utf8'),
        'collation' => env('CAPTAIN011_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('CAPTAIN011_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('CAPTAIN011_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_captain_012" => [
        'driver' => env('CAPTAIN012_DB_DRIVER', 'mysql'),
        'host' => env('CAPTAIN012_DB_HOST', 'localhost'),
        'database' => env('CAPTAIN012_DB_DATABASE', 'hyperf'),
        'port' => env('CAPTAIN012_DB_PORT', 3306),
        'username' => env('CAPTAIN012_DB_USERNAME', 'root'),
        'password' => env('CAPTAIN012_DB_PASSWORD', ''),
        'charset' => env('CAPTAIN012_DB_CHARSET', 'utf8'),
        'collation' => env('CAPTAIN012_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('CAPTAIN012_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('CAPTAIN012_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_captain_013" => [
        'driver' => env('CAPTAIN013_DB_DRIVER', 'mysql'),
        'host' => env('CAPTAIN013_DB_HOST', 'localhost'),
        'database' => env('CAPTAIN013_DB_DATABASE', 'hyperf'),
        'port' => env('CAPTAIN013_DB_PORT', 3306),
        'username' => env('CAPTAIN013_DB_USERNAME', 'root'),
        'password' => env('CAPTAIN013_DB_PASSWORD', ''),
        'charset' => env('CAPTAIN013_DB_CHARSET', 'utf8'),
        'collation' => env('CAPTAIN013_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('CAPTAIN013_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('CAPTAIN013_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_captain_014" => [
        'driver' => env('CAPTAIN014_DB_DRIVER', 'mysql'),
        'host' => env('CAPTAIN014_DB_HOST', 'localhost'),
        'database' => env('CAPTAIN014_DB_DATABASE', 'hyperf'),
        'port' => env('CAPTAIN014_DB_PORT', 3306),
        'username' => env('CAPTAIN014_DB_USERNAME', 'root'),
        'password' => env('CAPTAIN014_DB_PASSWORD', ''),
        'charset' => env('CAPTAIN014_DB_CHARSET', 'utf8'),
        'collation' => env('CAPTAIN014_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('CAPTAIN014_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('CAPTAIN014_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_captain_015" => [
        'driver' => env('CAPTAIN015_DB_DRIVER', 'mysql'),
        'host' => env('CAPTAIN015_DB_HOST', 'localhost'),
        'database' => env('CAPTAIN015_DB_DATABASE', 'hyperf'),
        'port' => env('CAPTAIN015_DB_PORT', 3306),
        'username' => env('CAPTAIN015_DB_USERNAME', 'root'),
        'password' => env('CAPTAIN015_DB_PASSWORD', ''),
        'charset' => env('CAPTAIN015_DB_CHARSET', 'utf8'),
        'collation' => env('CAPTAIN015_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('CAPTAIN015_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('CAPTAIN015_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_captain_016" => [
        'driver' => env('CAPTAIN016_DB_DRIVER', 'mysql'),
        'host' => env('CAPTAIN016_DB_HOST', 'localhost'),
        'database' => env('CAPTAIN016_DB_DATABASE', 'hyperf'),
        'port' => env('CAPTAIN016_DB_PORT', 3306),
        'username' => env('CAPTAIN016_DB_USERNAME', 'root'),
        'password' => env('CAPTAIN016_DB_PASSWORD', ''),
        'charset' => env('CAPTAIN016_DB_CHARSET', 'utf8'),
        'collation' => env('CAPTAIN016_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('CAPTAIN016_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('CAPTAIN016_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_finance_001" => [
        'driver' => env('FIANACE001_DB_DRIVER', 'mysql'),
        'host' => env('FIANACE001_DB_HOST', 'localhost'),
        'database' => env('FIANACE001_DB_DATABASE', 'hyperf'),
        'port' => env('FIANACE001_DB_PORT', 3306),
        'username' => env('FIANACE001_DB_USERNAME', 'root'),
        'password' => env('FIANACE001_DB_PASSWORD', ''),
        'charset' => env('FIANACE001_DB_CHARSET', 'utf8'),
        'collation' => env('FIANACE001_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('FIANACE001_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('FIANACE001_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_finance_002" => [
        'driver' => env('FIANACE002_DB_DRIVER', 'mysql'),
        'host' => env('FIANACE002_DB_HOST', 'localhost'),
        'database' => env('FIANACE002_DB_DATABASE', 'hyperf'),
        'port' => env('FIANACE002_DB_PORT', 3306),
        'username' => env('FIANACE002_DB_USERNAME', 'root'),
        'password' => env('FIANACE002_DB_PASSWORD', ''),
        'charset' => env('FIANACE002_DB_CHARSET', 'utf8'),
        'collation' => env('FIANACE002_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('FIANACE002_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('FIANACE002_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_finance_003" => [
        'driver' => env('FIANACE003_DB_DRIVER', 'mysql'),
        'host' => env('FIANACE003_DB_HOST', 'localhost'),
        'database' => env('FIANACE003_DB_DATABASE', 'hyperf'),
        'port' => env('FIANACE003_DB_PORT', 3306),
        'username' => env('FIANACE003_DB_USERNAME', 'root'),
        'password' => env('FIANACE003_DB_PASSWORD', ''),
        'charset' => env('FIANACE003_DB_CHARSET', 'utf8'),
        'collation' => env('FIANACE003_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('FIANACE003_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('FIANACE003_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_finance_004" => [
        'driver' => env('FIANACE004_DB_DRIVER', 'mysql'),
        'host' => env('FIANACE004_DB_HOST', 'localhost'),
        'database' => env('FIANACE004_DB_DATABASE', 'hyperf'),
        'port' => env('FIANACE004_DB_PORT', 3306),
        'username' => env('FIANACE004_DB_USERNAME', 'root'),
        'password' => env('FIANACE004_DB_PASSWORD', ''),
        'charset' => env('FIANACE004_DB_CHARSET', 'utf8'),
        'collation' => env('FIANACE004_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('FIANACE004_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('FIANACE004_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_finance_005" => [
        'driver' => env('FIANACE005_DB_DRIVER', 'mysql'),
        'host' => env('FIANACE005_DB_HOST', 'localhost'),
        'database' => env('FIANACE005_DB_DATABASE', 'hyperf'),
        'port' => env('FIANACE005_DB_PORT', 3306),
        'username' => env('FIANACE005_DB_USERNAME', 'root'),
        'password' => env('FIANACE005_DB_PASSWORD', ''),
        'charset' => env('FIANACE005_DB_CHARSET', 'utf8'),
        'collation' => env('FIANACE005_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('FIANACE005_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('FIANACE005_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_finance_006" => [
        'driver' => env('FIANACE006_DB_DRIVER', 'mysql'),
        'host' => env('FIANACE006_DB_HOST', 'localhost'),
        'database' => env('FIANACE006_DB_DATABASE', 'hyperf'),
        'port' => env('FIANACE006_DB_PORT', 3306),
        'username' => env('FIANACE006_DB_USERNAME', 'root'),
        'password' => env('FIANACE006_DB_PASSWORD', ''),
        'charset' => env('FIANACE006_DB_CHARSET', 'utf8'),
        'collation' => env('FIANACE006_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('FIANACE006_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('FIANACE006_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_finance_007" => [
        'driver' => env('FIANACE007_DB_DRIVER', 'mysql'),
        'host' => env('FIANACE007_DB_HOST', 'localhost'),
        'database' => env('FIANACE007_DB_DATABASE', 'hyperf'),
        'port' => env('FIANACE007_DB_PORT', 3306),
        'username' => env('FIANACE007_DB_USERNAME', 'root'),
        'password' => env('FIANACE007_DB_PASSWORD', ''),
        'charset' => env('FIANACE007_DB_CHARSET', 'utf8'),
        'collation' => env('FIANACE007_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('FIANACE007_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('FIANACE007_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_finance_008" => [
        'driver' => env('FIANACE008_DB_DRIVER', 'mysql'),
        'host' => env('FIANACE008_DB_HOST', 'localhost'),
        'database' => env('FIANACE008_DB_DATABASE', 'hyperf'),
        'port' => env('FIANACE008_DB_PORT', 3306),
        'username' => env('FIANACE008_DB_USERNAME', 'root'),
        'password' => env('FIANACE008_DB_PASSWORD', ''),
        'charset' => env('FIANACE008_DB_CHARSET', 'utf8'),
        'collation' => env('FIANACE008_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('FIANACE008_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('FIANACE008_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_finance_009" => [
        'driver' => env('FIANACE009_DB_DRIVER', 'mysql'),
        'host' => env('FIANACE009_DB_HOST', 'localhost'),
        'database' => env('FIANACE009_DB_DATABASE', 'hyperf'),
        'port' => env('FIANACE009_DB_PORT', 3306),
        'username' => env('FIANACE009_DB_USERNAME', 'root'),
        'password' => env('FIANACE009_DB_PASSWORD', ''),
        'charset' => env('FIANACE009_DB_CHARSET', 'utf8'),
        'collation' => env('FIANACE009_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('FIANACE009_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('FIANACE009_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_finance_010" => [
        'driver' => env('FIANACE010_DB_DRIVER', 'mysql'),
        'host' => env('FIANACE010_DB_HOST', 'localhost'),
        'database' => env('FIANACE010_DB_DATABASE', 'hyperf'),
        'port' => env('FIANACE010_DB_PORT', 3306),
        'username' => env('FIANACE010_DB_USERNAME', 'root'),
        'password' => env('FIANACE010_DB_PASSWORD', ''),
        'charset' => env('FIANACE010_DB_CHARSET', 'utf8'),
        'collation' => env('FIANACE010_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('FIANACE010_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('FIANACE010_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_finance_011" => [
        'driver' => env('FIANACE011_DB_DRIVER', 'mysql'),
        'host' => env('FIANACE011_DB_HOST', 'localhost'),
        'database' => env('FIANACE011_DB_DATABASE', 'hyperf'),
        'port' => env('FIANACE011_DB_PORT', 3306),
        'username' => env('FIANACE011_DB_USERNAME', 'root'),
        'password' => env('FIANACE011_DB_PASSWORD', ''),
        'charset' => env('FIANACE011_DB_CHARSET', 'utf8'),
        'collation' => env('FIANACE011_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('FIANACE011_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('FIANACE011_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_finance_012" => [
        'driver' => env('FIANACE012_DB_DRIVER', 'mysql'),
        'host' => env('FIANACE012_DB_HOST', 'localhost'),
        'database' => env('FIANACE012_DB_DATABASE', 'hyperf'),
        'port' => env('FIANACE012_DB_PORT', 3306),
        'username' => env('FIANACE012_DB_USERNAME', 'root'),
        'password' => env('FIANACE012_DB_PASSWORD', ''),
        'charset' => env('FIANACE012_DB_CHARSET', 'utf8'),
        'collation' => env('FIANACE012_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('FIANACE012_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('FIANACE012_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_finance_013" => [
        'driver' => env('FIANACE013_DB_DRIVER', 'mysql'),
        'host' => env('FIANACE013_DB_HOST', 'localhost'),
        'database' => env('FIANACE013_DB_DATABASE', 'hyperf'),
        'port' => env('FIANACE013_DB_PORT', 3306),
        'username' => env('FIANACE013_DB_USERNAME', 'root'),
        'password' => env('FIANACE013_DB_PASSWORD', ''),
        'charset' => env('FIANACE013_DB_CHARSET', 'utf8'),
        'collation' => env('FIANACE013_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('FIANACE013_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('FIANACE013_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_finance_014" => [
        'driver' => env('FIANACE014_DB_DRIVER', 'mysql'),
        'host' => env('FIANACE014_DB_HOST', 'localhost'),
        'database' => env('FIANACE014_DB_DATABASE', 'hyperf'),
        'port' => env('FIANACE014_DB_PORT', 3306),
        'username' => env('FIANACE014_DB_USERNAME', 'root'),
        'password' => env('FIANACE014_DB_PASSWORD', ''),
        'charset' => env('FIANACE014_DB_CHARSET', 'utf8'),
        'collation' => env('FIANACE014_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('FIANACE014_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('FIANACE014_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_finance_015" => [
        'driver' => env('FIANACE015_DB_DRIVER', 'mysql'),
        'host' => env('FIANACE015_DB_HOST', 'localhost'),
        'database' => env('FIANACE015_DB_DATABASE', 'hyperf'),
        'port' => env('FIANACE015_DB_PORT', 3306),
        'username' => env('FIANACE015_DB_USERNAME', 'root'),
        'password' => env('FIANACE015_DB_PASSWORD', ''),
        'charset' => env('FIANACE015_DB_CHARSET', 'utf8'),
        'collation' => env('FIANACE015_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('FIANACE015_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('FIANACE015_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_finance_016" => [
        'driver' => env('FIANACE016_DB_DRIVER', 'mysql'),
        'host' => env('FIANACE016_DB_HOST', 'localhost'),
        'database' => env('FIANACE016_DB_DATABASE', 'hyperf'),
        'port' => env('FIANACE016_DB_PORT', 3306),
        'username' => env('FIANACE016_DB_USERNAME', 'root'),
        'password' => env('FIANACE016_DB_PASSWORD', ''),
        'charset' => env('FIANACE016_DB_CHARSET', 'utf8'),
        'collation' => env('FIANACE016_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('FIANACE016_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('FIANACE016_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_goods_001" => [
        'driver' => env('GOODS001_DB_DRIVER', 'mysql'),
        'host' => env('GOODS001_DB_HOST', 'localhost'),
        'database' => env('GOODS001_DB_DATABASE', 'hyperf'),
        'port' => env('GOODS001_DB_PORT', 3306),
        'username' => env('GOODS001_DB_USERNAME', 'root'),
        'password' => env('GOODS001_DB_PASSWORD', ''),
        'charset' => env('GOODS001_DB_CHARSET', 'utf8'),
        'collation' => env('GOODS001_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('GOODS001_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('GOODS001_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_goods_002" => [
        'driver' => env('GOODS002_DB_DRIVER', 'mysql'),
        'host' => env('GOODS002_DB_HOST', 'localhost'),
        'database' => env('GOODS002_DB_DATABASE', 'hyperf'),
        'port' => env('GOODS002_DB_PORT', 3306),
        'username' => env('GOODS002_DB_USERNAME', 'root'),
        'password' => env('GOODS002_DB_PASSWORD', ''),
        'charset' => env('GOODS002_DB_CHARSET', 'utf8'),
        'collation' => env('GOODS002_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('GOODS002_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('GOODS002_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_goods_003" => [
        'driver' => env('GOODS003_DB_DRIVER', 'mysql'),
        'host' => env('GOODS003_DB_HOST', 'localhost'),
        'database' => env('GOODS003_DB_DATABASE', 'hyperf'),
        'port' => env('GOODS003_DB_PORT', 3306),
        'username' => env('GOODS003_DB_USERNAME', 'root'),
        'password' => env('GOODS003_DB_PASSWORD', ''),
        'charset' => env('GOODS003_DB_CHARSET', 'utf8'),
        'collation' => env('GOODS003_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('GOODS003_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('GOODS003_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_goods_004" => [
        'driver' => env('GOODS004_DB_DRIVER', 'mysql'),
        'host' => env('GOODS004_DB_HOST', 'localhost'),
        'database' => env('GOODS004_DB_DATABASE', 'hyperf'),
        'port' => env('GOODS004_DB_PORT', 3306),
        'username' => env('GOODS004_DB_USERNAME', 'root'),
        'password' => env('GOODS004_DB_PASSWORD', ''),
        'charset' => env('GOODS004_DB_CHARSET', 'utf8'),
        'collation' => env('GOODS004_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('GOODS004_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('GOODS004_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_goods_005" => [
        'driver' => env('GOODS005_DB_DRIVER', 'mysql'),
        'host' => env('GOODS005_DB_HOST', 'localhost'),
        'database' => env('GOODS005_DB_DATABASE', 'hyperf'),
        'port' => env('GOODS005_DB_PORT', 3306),
        'username' => env('GOODS005_DB_USERNAME', 'root'),
        'password' => env('GOODS005_DB_PASSWORD', ''),
        'charset' => env('GOODS005_DB_CHARSET', 'utf8'),
        'collation' => env('GOODS005_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('GOODS005_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('GOODS005_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_goods_006" => [
        'driver' => env('GOODS006_DB_DRIVER', 'mysql'),
        'host' => env('GOODS006_DB_HOST', 'localhost'),
        'database' => env('GOODS006_DB_DATABASE', 'hyperf'),
        'port' => env('GOODS006_DB_PORT', 3306),
        'username' => env('GOODS006_DB_USERNAME', 'root'),
        'password' => env('GOODS006_DB_PASSWORD', ''),
        'charset' => env('GOODS006_DB_CHARSET', 'utf8'),
        'collation' => env('GOODS006_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('GOODS006_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('GOODS006_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_goods_007" => [
        'driver' => env('GOODS007_DB_DRIVER', 'mysql'),
        'host' => env('GOODS007_DB_HOST', 'localhost'),
        'database' => env('GOODS007_DB_DATABASE', 'hyperf'),
        'port' => env('GOODS007_DB_PORT', 3306),
        'username' => env('GOODS007_DB_USERNAME', 'root'),
        'password' => env('GOODS007_DB_PASSWORD', ''),
        'charset' => env('GOODS007_DB_CHARSET', 'utf8'),
        'collation' => env('GOODS007_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('GOODS007_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('GOODS007_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_goods_008" => [
        'driver' => env('GOODS008_DB_DRIVER', 'mysql'),
        'host' => env('GOODS008_DB_HOST', 'localhost'),
        'database' => env('GOODS008_DB_DATABASE', 'hyperf'),
        'port' => env('GOODS008_DB_PORT', 3306),
        'username' => env('GOODS008_DB_USERNAME', 'root'),
        'password' => env('GOODS008_DB_PASSWORD', ''),
        'charset' => env('GOODS008_DB_CHARSET', 'utf8'),
        'collation' => env('GOODS008_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('GOODS008_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('GOODS008_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_goods_009" => [
        'driver' => env('GOODS009_DB_DRIVER', 'mysql'),
        'host' => env('GOODS009_DDB_HOST', 'localhost'),
        'database' => env('GOODS009_DDB_DATABASE', 'hyperf'),
        'port' => env('GOODS009_DDB_PORT', 3306),
        'username' => env('GOODS009_DDB_USERNAME', 'root'),
        'password' => env('GOODS009_DDB_PASSWORD', ''),
        'charset' => env('GOODS009_DDB_CHARSET', 'utf8'),
        'collation' => env('GOODS009_DDB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('GOODS009_DDB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('GOODS009_DDB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_goods_010" => [
        'driver' => env('GOODS010_DDB_DRIVER', 'mysql'),
        'host' => env('GOODS010_DB_HOST', 'localhost'),
        'database' => env('GOODS010_DB_DATABASE', 'hyperf'),
        'port' => env('GOODS010_DB_PORT', 3306),
        'username' => env('GOODS010_DB_USERNAME', 'root'),
        'password' => env('GOODS010_DB_PASSWORD', ''),
        'charset' => env('GOODS010_DB_CHARSET', 'utf8'),
        'collation' => env('GOODS010_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('GOODS010_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('GOODS010_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_goods_011" => [
        'driver' => env('GOODS011_DB_DRIVER', 'mysql'),
        'host' => env('GOODS011_DB_HOST', 'localhost'),
        'database' => env('GOODS011_DB_DATABASE', 'hyperf'),
        'port' => env('GOODS011_DB_PORT', 3306),
        'username' => env('GOODS011_DB_USERNAME', 'root'),
        'password' => env('GOODS011_DB_PASSWORD', ''),
        'charset' => env('GOODS011_DB_CHARSET', 'utf8'),
        'collation' => env('GOODS011_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('GOODS011_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('GOODS011_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_goods_012" => [
        'driver' => env('GOODS012_DB_DRIVER', 'mysql'),
        'host' => env('GOODS012_DB_HOST', 'localhost'),
        'database' => env('GOODS012_DB_DATABASE', 'hyperf'),
        'port' => env('GOODS012_DB_PORT', 3306),
        'username' => env('GOODS012_DB_USERNAME', 'root'),
        'password' => env('GOODS012_DB_PASSWORD', ''),
        'charset' => env('GOODS012_DB_CHARSET', 'utf8'),
        'collation' => env('GOODS012_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('GOODS012_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('GOODS012_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_goods_013" => [
        'driver' => env('GOODS013_DB_DRIVER', 'mysql'),
        'host' => env('GOODS013_DB_HOST', 'localhost'),
        'database' => env('GOODS013_DB_DATABASE', 'hyperf'),
        'port' => env('GOODS013_DB_PORT', 3306),
        'username' => env('GOODS013_DB_USERNAME', 'root'),
        'password' => env('GOODS013_DB_PASSWORD', ''),
        'charset' => env('GOODS013_DB_CHARSET', 'utf8'),
        'collation' => env('GOODS013_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('GOODS013_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('GOODS013_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_goods_014" => [
        'driver' => env('GOODS014_DB_DRIVER', 'mysql'),
        'host' => env('GOODS014_DB_HOST', 'localhost'),
        'database' => env('GOODS014_DB_DATABASE', 'hyperf'),
        'port' => env('GOODS014_DB_PORT', 3306),
        'username' => env('GOODS014_DB_USERNAME', 'root'),
        'password' => env('GOODS014_DB_PASSWORD', ''),
        'charset' => env('GOODS014_DB_CHARSET', 'utf8'),
        'collation' => env('GOODS014_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('GOODS014_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('GOODS014_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_goods_015" => [
        'driver' => env('GOODS015_DB_DRIVER', 'mysql'),
        'host' => env('GOODS015_DB_HOST', 'localhost'),
        'database' => env('GOODS015_DB_DATABASE', 'hyperf'),
        'port' => env('GOODS015_DB_PORT', 3306),
        'username' => env('GOODS015_DB_USERNAME', 'root'),
        'password' => env('GOODS015_DB_PASSWORD', ''),
        'charset' => env('GOODS015_DB_CHARSET', 'utf8'),
        'collation' => env('GOODS015_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('GOODS015_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('GOODS015_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_goods_016" => [
        'driver' => env('GOODS016_DB_DRIVER', 'mysql'),
        'host' => env('GOODS016_DB_HOST', 'localhost'),
        'database' => env('GOODS016_DB_DATABASE', 'hyperf'),
        'port' => env('GOODS016_DB_PORT', 3306),
        'username' => env('GOODS016_DB_USERNAME', 'root'),
        'password' => env('GOODS016_DB_PASSWORD', ''),
        'charset' => env('GOODS016_DB_CHARSET', 'utf8'),
        'collation' => env('GOODS016_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('GOODS016_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('GOODS016_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_log" => [
        'driver' => env('LOG_DB_DRIVER', 'mysql'),
        'host' => env('LOG_DB_HOST', 'localhost'),
        'database' => env('LOG_DB_DATABASE', 'hyperf'),
        'port' => env('LOG_DB_PORT', 3306),
        'username' => env('LOG_DB_USERNAME', 'root'),
        'password' => env('LOG_DB_PASSWORD', ''),
        'charset' => env('LOG_DB_CHARSET', 'utf8'),
        'collation' => env('LOG_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('LOG_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('LOG_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_polling" => [
        'driver' => env('POLLING_DB_DRIVER', 'mysql'),
        'host' => env('POLLING_DB_HOST', 'localhost'),
        'database' => env('POLLING_DB_DATABASE', 'hyperf'),
        'port' => env('POLLING_DB_PORT', 3306),
        'username' => env('POLLING_DB_USERNAME', 'root'),
        'password' => env('POLLING_DB_PASSWORD', ''),
        'charset' => env('POLLING_DB_CHARSET', 'utf8'),
        'collation' => env('POLLING_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('POLLING_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('POLLING_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_report" => [
        'driver' => env('REPORT_DB_DRIVER', 'mysql'),
        'host' => env('REPORT_DB_HOST', 'localhost'),
        'database' => env('REPORT_DB_DATABASE', 'hyperf'),
        'port' => env('REPORT_DB_PORT', 3306),
        'username' => env('REPORT_DB_USERNAME', 'root'),
        'password' => env('REPORT_DB_PASSWORD', ''),
        'charset' => env('REPORT_DB_CHARSET', 'utf8'),
        'collation' => env('REPORT_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('REPORT_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('REPORT_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_trade_001" => [
        'driver' => env('TRADE001_DB_DRIVER', 'mysql'),
        'host' => env('TRADE001_DB_HOST', 'localhost'),
        'database' => env('TRADE001_DB_DATABASE', 'hyperf'),
        'port' => env('TRADE001_DB_PORT', 3306),
        'username' => env('TRADE001_DB_USERNAME', 'root'),
        'password' => env('TRADE001_DB_PASSWORD', ''),
        'charset' => env('TRADE001_DB_CHARSET', 'utf8'),
        'collation' => env('TRADE001_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('TRADE001_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('TRADE001_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_trade_002" => [
        'driver' => env('TRADE002_DB_DRIVER', 'mysql'),
        'host' => env('TRADE002_DB_HOST', 'localhost'),
        'database' => env('TRADE002_DB_DATABASE', 'hyperf'),
        'port' => env('TRADE002_DB_PORT', 3306),
        'username' => env('TRADE002_DB_USERNAME', 'root'),
        'password' => env('TRADE002_DB_PASSWORD', ''),
        'charset' => env('TRADE002_DB_CHARSET', 'utf8'),
        'collation' => env('TRADE002_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('TRADE002_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('TRADE002_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_trade_003" => [
        'driver' => env('TRADE003_DB_DRIVER', 'mysql'),
        'host' => env('TRADE003_DB_HOST', 'localhost'),
        'database' => env('TRADE003_DB_DATABASE', 'hyperf'),
        'port' => env('TRADE003_DB_PORT', 3306),
        'username' => env('TRADE003_DB_USERNAME', 'root'),
        'password' => env('TRADE003_DB_PASSWORD', ''),
        'charset' => env('TRADE003_DB_CHARSET', 'utf8'),
        'collation' => env('TRADE003_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('TRADE003_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('TRADE003_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_trade_004" => [
        'driver' => env('TRADE004_DB_DRIVER', 'mysql'),
        'host' => env('TRADE004_DB_HOST', 'localhost'),
        'database' => env('TRADE004_DB_DATABASE', 'hyperf'),
        'port' => env('TRADE004_DB_PORT', 3306),
        'username' => env('TRADE004_DB_USERNAME', 'root'),
        'password' => env('TRADE004_DB_PASSWORD', ''),
        'charset' => env('TRADE004_DB_CHARSET', 'utf8'),
        'collation' => env('TRADE004_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('TRADE004_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('TRADE004_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_trade_005" => [
        'driver' => env('TRADE005_DB_DRIVER', 'mysql'),
        'host' => env('TRADE005_DB_HOST', 'localhost'),
        'database' => env('TRADE005_DB_DATABASE', 'hyperf'),
        'port' => env('TRADE005_DB_PORT', 3306),
        'username' => env('TRADE005_DB_USERNAME', 'root'),
        'password' => env('TRADE005_DB_PASSWORD', ''),
        'charset' => env('TRADE005_DB_CHARSET', 'utf8'),
        'collation' => env('TRADE005_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('TRADE005_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('TRADE005_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_trade_006" => [
        'driver' => env('TRADE006_DB_DRIVER', 'mysql'),
        'host' => env('TRADE006_DB_HOST', 'localhost'),
        'database' => env('TRADE006_DB_DATABASE', 'hyperf'),
        'port' => env('TRADE006_DB_PORT', 3306),
        'username' => env('TRADE006_DB_USERNAME', 'root'),
        'password' => env('TRADE006_DB_PASSWORD', ''),
        'charset' => env('TRADE006_DB_CHARSET', 'utf8'),
        'collation' => env('TRADE006_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('TRADE006_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('TRADE006_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_trade_007" => [
        'driver' => env('TRADE007_DB_DRIVER', 'mysql'),
        'host' => env('TRADE007_DB_HOST', 'localhost'),
        'database' => env('TRADE007_DB_DATABASE', 'hyperf'),
        'port' => env('TRADE007_DB_PORT', 3306),
        'username' => env('TRADE007_DB_USERNAME', 'root'),
        'password' => env('TRADE007_DB_PASSWORD', ''),
        'charset' => env('TRADE007_DB_CHARSET', 'utf8'),
        'collation' => env('TRADE007_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('TRADE007_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('TRADE007_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_trade_008" => [
        'driver' => env('TRADE008_DB_DRIVER', 'mysql'),
        'host' => env('TRADE008_DB_HOST', 'localhost'),
        'database' => env('TRADE008_DB_DATABASE', 'hyperf'),
        'port' => env('TRADE008_DB_PORT', 3306),
        'username' => env('TRADE008_DB_USERNAME', 'root'),
        'password' => env('TRADE008_DB_PASSWORD', ''),
        'charset' => env('TRADE008_DB_CHARSET', 'utf8'),
        'collation' => env('TRADE008_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('TRADE008_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('TRADE008_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_trade_009" => [
        'driver' => env('TRADE009_DB_DRIVER', 'mysql'),
        'host' => env('TRADE009_DB_HOST', 'localhost'),
        'database' => env('TRADE009_DB_DATABASE', 'hyperf'),
        'port' => env('TRADE009_DB_PORT', 3306),
        'username' => env('TRADE009_DB_USERNAME', 'root'),
        'password' => env('TRADE009_DB_PASSWORD', ''),
        'charset' => env('TRADE009_DB_CHARSET', 'utf8'),
        'collation' => env('TRADE009_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('TRADE009_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('TRADE009_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_trade_010" => [
        'driver' => env('TRADE010_DB_DRIVER', 'mysql'),
        'host' => env('TRADE010_DB_HOST', 'localhost'),
        'database' => env('TRADE010_DB_DATABASE', 'hyperf'),
        'port' => env('TRADE010_DB_PORT', 3306),
        'username' => env('TRADE010_DB_USERNAME', 'root'),
        'password' => env('TRADE010_DB_PASSWORD', ''),
        'charset' => env('TRADE010_DB_CHARSET', 'utf8'),
        'collation' => env('TRADE010_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('TRADE010_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('TRADE010_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_trade_011" => [
        'driver' => env('TRADE011_DB_DRIVER', 'mysql'),
        'host' => env('TRADE011_DB_HOST', 'localhost'),
        'database' => env('TRADE011_DB_DATABASE', 'hyperf'),
        'port' => env('TRADE011_DB_PORT', 3306),
        'username' => env('TRADE011_DB_USERNAME', 'root'),
        'password' => env('TRADE011_DB_PASSWORD', ''),
        'charset' => env('TRADE011_DB_CHARSET', 'utf8'),
        'collation' => env('TRADE011_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('TRADE011_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('TRADE011_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_trade_012" => [
        'driver' => env('TRADE012_DB_DRIVER', 'mysql'),
        'host' => env('TRADE012_DB_HOST', 'localhost'),
        'database' => env('TRADE012_DB_DATABASE', 'hyperf'),
        'port' => env('TRADE012_DB_PORT', 3306),
        'username' => env('TRADE012_DB_USERNAME', 'root'),
        'password' => env('TRADE012_DB_PASSWORD', ''),
        'charset' => env('TRADE012_DB_CHARSET', 'utf8'),
        'collation' => env('TRADE012_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('TRADE012_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('TRADE012_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_trade_013" => [
        'driver' => env('TRADE013_DB_DRIVER', 'mysql'),
        'host' => env('TRADE013_DB_HOST', 'localhost'),
        'database' => env('TRADE013_DB_DATABASE', 'hyperf'),
        'port' => env('TRADE013_DB_PORT', 3306),
        'username' => env('TRADE013_DB_USERNAME', 'root'),
        'password' => env('TRADE013_DB_PASSWORD', ''),
        'charset' => env('TRADE013_DB_CHARSET', 'utf8'),
        'collation' => env('TRADE013_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('TRADE013_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('TRADE013_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_trade_014" => [
        'driver' => env('TRADE014_DB_DRIVER', 'mysql'),
        'host' => env('TRADE014_DB_HOST', 'localhost'),
        'database' => env('TRADE014_DB_DATABASE', 'hyperf'),
        'port' => env('TRADE014_DB_PORT', 3306),
        'username' => env('TRADE014_DB_USERNAME', 'root'),
        'password' => env('TRADE014_DB_PASSWORD', ''),
        'charset' => env('TRADE014_DB_CHARSET', 'utf8'),
        'collation' => env('TRADE014_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('TRADE014_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('TRADE014_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_trade_015" => [
        'driver' => env('TRADE015_DB_DRIVER', 'mysql'),
        'host' => env('TRADE015_DB_HOST', 'localhost'),
        'database' => env('TRADE015_DB_DATABASE', 'hyperf'),
        'port' => env('TRADE015_DB_PORT', 3306),
        'username' => env('TRADE015_DB_USERNAME', 'root'),
        'password' => env('TRADE015_DB_PASSWORD', ''),
        'charset' => env('TRADE015_DB_CHARSET', 'utf8'),
        'collation' => env('TRADE015_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('TRADE015_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('TRADE015_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
    "erp_trade_016" => [
        'driver' => env('TRADE016_DB_DRIVER', 'mysql'),
        'host' => env('TRADE016_DB_HOST', 'localhost'),
        'database' => env('TRADE016_DB_DATABASE', 'hyperf'),
        'port' => env('TRADE016_DB_PORT', 3306),
        'username' => env('TRADE016_DB_USERNAME', 'root'),
        'password' => env('TRADE016_DB_PASSWORD', ''),
        'charset' => env('TRADE016_DB_CHARSET', 'utf8'),
        'collation' => env('TRADE016_DB_COLLATION', 'utf8_unicode_ci'),
        'prefix' => env('TRADE016_DB_PREFIX', ''),
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 100,
            'connect_timeout' => 30.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
            'max_idle_time' => (float) env('TRADE016_DB_MAX_IDLE_TIME', 60),
        ],
        'commands' => [
            'gen:model' => [
                'path' => 'app/Model',
                'force_casts' => true,
                'inheritance' => 'Model',
            ],
        ],
    ] ,
];
